core_default_homepage:
    path:     /
    defaults: { _controller: CoreDefaultBundle:Default:index }
core_default_descargas:
    pattern: /descargas/
    defaults: { _controller: CoreDefaultBundle:Default:descargas }
core_default_documentacion:
    pattern: /documentacion/
    defaults: { _controller: CoreDefaultBundle:Default:documentacion }
core_default_catalogo:
    pattern: /catalogo/
    defaults: { _controller: CoreDefaultBundle:Default:catalogo }
core_default_involucrarse:
    pattern: /catalogo/
    defaults: { _controller: CoreDefaultBundle:Default:involucrarse }
core_default_buscar:
    pattern: /buscar/
    defaults: { _controller: CoreDefaultBundle:Default:involucrarse }